### ISSUE TITLE
Warrior 'Current Project' page blank 

### ISSUE THREAD

**Issue by mhkohne** [ArchiveTeam/seesaw-kit#102]
I recently installed the Warrior (v2-20121008). I've presently got it working on the IMDB project, and when I go to the 'current project' tab, I get nothing. 

I'm setup to only do one item at a time.

Switching to the URLTeam 2 project and the Current Project page shows up just fine.

**Comment by Fornax96** [comment]
I tried all the projects in the list, but URLTeam 2 is the only one which displays anything on the Current Project page. All the other projects just display "The warrior is beginning work on a project." on the sidebar and then continue doing nothing.

**Comment by chfoo** [comment]
I'm trying to debug this but it looks like like either a project's `warrior-install.sh` or `pipeline.py` is invalid and causing the warrior to hang. As soon as you select a broken project, the warrior won't function correctly.

My advice to try running a project and see if it starts. If it doesn't, make sure to stop the project, reboot, and try again. If it doesn't appear to work, contact whoever is in charge of the project and see if they have it working in the warrior.

----

There appears to be many places that can error due to project errors which are discarded from the event loop. As well, `AsyncProc2` is using `tornado.process.Subprocess` which seems to hang the event loop much after where an error occurs probably due to streams blocking.

**Comment by nebog** [comment]
I have same problem, warrior works only with URLTeam 2 project, won't work with other open projects, I tried all. 
The bug has not been fixed yet?

**Comment by BurritoWrapped** [comment]
I'm pretty sure the project is kind of dead at this point. There hasn't been a commit in 3+ years ago.

**Comment by chfoo** [comment]
**Update: Please disregard the project readme files about Warrior VM compatibility. They're wrong and not working within the Warrior VM appliance.** Unfortunately, only running Docker yourself is working right now.

---

The blank page is likely the result of the selected Warrior project failing to install because Seesaw is not running in a compatible 
environment. 

* Check that you are running the [latest Warrior VM appliance](https://github.com/ArchiveTeam/Ubuntu-Warrior/releases).
* Check the the debug log in the About tab.
  * Look and see if there is a message about the selected project failing to install.
* Please check the selected project's readme file for compatibility notes. (Check the archiveteam.org wiki for the repository or see the [ArchiveTeam's GitHub organization](https://github.com/ArchiveTeam/) for a full list).
  * If the Warrior VM appliance is not supported, you may try running it [manually with Docker](https://github.com/ArchiveTeam/warrior-dockerfile) and following the instructions specified in that project's readme file to install required dependencies.
* If the selected project supports the Warrior VM appliance and the project requests it, install the Extras Project. (This is experimental. Only x86 supported, see [the notes](https://github.com/ArchiveTeam/warrior-extras-installer).)
* Join the relevant project IRC channel as noted in the archiveteam.org wiki page for the selected project, or join the ["#warrior" IRC channel](https://archiveteam.org/index.php?title=Archiveteam:IRC) to get latest news or ask for help. 

There is currently no activity in this repo but issues are being discussed on IRC and being worked on.

**Comment by VADemon** [comment]
@chfoo Just imported the new 3.1 warrior: it can't find wget-lua (from the About tab)

```2020-11-14 12:30:51,360 - seesaw.warrior - DEBUG - Update warrior hq.
2020-11-14 12:30:51,360 - seesaw.warrior - DEBUG - Warrior ID ''.
2020-11-14 12:30:51,639 - seesaw.warrior - DEBUG - Select project kinja
2020-11-14 12:30:51,639 - seesaw.warrior - DEBUG - Start selected project kinja (reinstall=False)
2020-11-14 12:30:51,640 - seesaw.warrior - DEBUG - Install project kinja
2020-11-14 12:30:51,734 - seesaw.warrior - DEBUG - git pull from https://github.com/ArchiveTeam/kinja-grab
2020-11-14 12:30:52,395 - seesaw.warrior - DEBUG - git operation: Already up to date.

2020-11-14 12:30:52,396 - seesaw.warrior - DEBUG - Install complete Already up to date.

2020-11-14 12:30:52,396 - seesaw.warrior - DEBUG - Result of the install process: True
2020-11-14 12:30:52,397 - seesaw.warrior - DEBUG - Clone project kinja /home/warrior/projects/kinja
2020-11-14 12:30:52,399 - seesaw.warrior - DEBUG - Cloning version e2b6dae
2020-11-14 12:30:52,400 - seesaw.warrior - DEBUG - Load pipeline /data/data/projects/kinja-e2b6dae/pipeline.py
2020-11-14 12:30:52,410 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2020-11-14 12:30:52,410 - seesaw.warrior - DEBUG - Executing pipeline
2020-11-14 12:30:52,419 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 737, in start_selected_project
    pipeline_path, {"downloader": self.downloader})
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 45, in <module>
Exception: No usable Wget+Lua found.
2020-11-14 12:30:52,419 - seesaw.warrior - WARNING - Project kinja did not install correctly and we're ignoring this problem.
2020-11-14 12:40:51,360 - seesaw.warrior - DEBUG - Update warrior hq.
2020-11-14 12:40:51,360 - seesaw.warrior - DEBUG - Warrior ID ''.
2020-11-14 12:40:51,845 - seesaw.warrior - DEBUG - Select project kinja
2020-11-14 12:48:15,374 - seesaw.warrior - DEBUG - Select project githubtest2
2020-11-14 12:48:15,374 - seesaw.warrior - DEBUG - Start selected project githubtest2 (reinstall=False)
2020-11-14 12:48:15,374 - seesaw.warrior - DEBUG - Install project githubtest2
2020-11-14 12:48:15,375 - seesaw.warrior - DEBUG - git clone
2020-11-14 12:48:16,758 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/githubtest2'...

2020-11-14 12:48:16,759 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/githubtest2'...

2020-11-14 12:48:16,759 - seesaw.warrior - DEBUG - Result of the install process: True
2020-11-14 12:48:16,759 - seesaw.warrior - DEBUG - Clone project githubtest2 /home/warrior/projects/githubtest2
2020-11-14 12:48:16,762 - seesaw.warrior - DEBUG - Cloning version a2a0b33
2020-11-14 12:48:16,817 - seesaw.warrior - DEBUG - Load pipeline /data/data/projects/githubtest2-a2a0b33/pipeline.py
2020-11-14 12:48:16,818 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2020-11-14 12:48:16,818 - seesaw.warrior - DEBUG - Executing pipeline
2020-11-14 12:48:17,361 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 737, in start_selected_project
    pipeline_path, {"downloader": self.downloader})
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 53, in <module>
Exception: No usable Wget+At found.
2020-11-14 12:48:17,361 - seesaw.warrior - WARNING - Project githubtest2 did not install correctly and we're ignoring this problem.
2020-11-14 12:50:51,371 - seesaw.warrior - DEBUG - Update warrior hq.
2020-11-14 12:50:51,371 - seesaw.warrior - DEBUG - Warrior ID ''.
2020-11-14 12:50:51,650 - seesaw.warrior - DEBUG - Select project githubtest2
2020-11-14 13:00:51,361 - seesaw.warrior - DEBUG - Update warrior hq.
2020-11-14 13:00:51,361 - seesaw.warrior - DEBUG - Warrior ID ''.
2020-11-14 13:00:51,425 - seesaw.warrior - DEBUG - Update project.
2020-11-14 13:00:51,426 - seesaw.warrior - DEBUG - Check project has update githubtest2
2020-11-14 13:00:51,431 - seesaw.warrior - DEBUG - git fetch
2020-11-14 13:00:51,669 - seesaw.warrior - DEBUG - Select project githubtest2
2020-11-14 13:00:51,978 - seesaw.warrior - DEBUG - False```

**Comment by chfoo** [comment]
> @chfoo Just imported the new 3.1 warrior: it can't find wget-lua (from the About tab)
> 

I'm aware. The projects weren't written to be properly compatible with the Warrior VM and the projects' readme files shouldn't say they are compatible.

**Comment by Arkiver2** [comment]
Closing as not relevant to seesaw-kit.
