### ISSUE TITLE
Can't run current project (ACIDplanet) after clean install

### ISSUE THREAD

**Issue by steverobbins** [ArchiveTeam/seesaw-kit#105]
Sorry if I'm posting this in the wrong repo, but it seems to be an issue for other projects, too.

I've just download the warrior for VirtualBox, running on Mac, and after installing, adding a nick name, and selecting ArchiveTeam's Choice, nothing happens.

```
2018-05-31 20:52:10,126 - seesaw.warrior - DEBUG - Update warrior hq.
2018-05-31 20:52:10,127 - seesaw.warrior - DEBUG - Warrior ID '17878'.
2018-05-31 20:53:54,119 - seesaw.warrior - DEBUG - Select project auto
2018-05-31 20:53:54,119 - seesaw.warrior - DEBUG - Update warrior hq.
2018-05-31 20:53:54,119 - seesaw.warrior - DEBUG - Warrior ID '17878'.
2018-05-31 20:53:54,239 - seesaw.warrior - DEBUG - Select project acidplanet
2018-05-31 20:53:54,240 - seesaw.warrior - DEBUG - Start selected project acidplanet (reinstall=False)
2018-05-31 20:53:54,240 - seesaw.warrior - DEBUG - Install project acidplanet
2018-05-31 20:53:54,240 - seesaw.warrior - DEBUG - git clone
2018-05-31 20:53:55,119 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/acidplanet'...

2018-05-31 20:53:55,121 - seesaw.warrior - ERROR - Custom project install file error
Traceback (most recent call last):
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 507, in install_project
    p.run()
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/externalprocess.py", line 142, in run
    self.pipe = tornado.process.Subprocess(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/process.py", line 244, in __init__
    self.proc = subprocess.Popen(*args, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
2018-05-31 20:53:55,125 - seesaw.warrior - ERROR - Custom installer failed to install: Cloning into '/home/warrior/projects/acidplanet'...
[Errno 8] Exec format error
Custom installer returned 9999

2018-05-31 20:54:57,854 - seesaw.warrior - DEBUG - Select project acidplanet
2018-05-31 20:55:01,748 - seesaw.warrior - DEBUG - Select project None
2018-05-31 20:55:01,748 - seesaw.warrior - DEBUG - Project doesn't exist.
2018-05-31 20:55:01,748 - seesaw.warrior - DEBUG - Start selected project None (reinstall=False)
2018-05-31 20:55:01,748 - seesaw.warrior - DEBUG - Project does not exist.
2018-05-31 20:55:03,584 - seesaw.warrior - DEBUG - Select project auto
2018-05-31 20:55:03,584 - seesaw.warrior - DEBUG - Update warrior hq.
2018-05-31 20:55:03,584 - seesaw.warrior - DEBUG - Warrior ID '17878'.
2018-05-31 20:55:08,602 - seesaw.warrior - DEBUG - Select project auto
2018-05-31 20:55:08,602 - seesaw.warrior - DEBUG - Update warrior hq.
2018-05-31 20:55:08,602 - seesaw.warrior - DEBUG - Warrior ID '17878'.
2018-05-31 20:55:08,748 - seesaw.warrior - DEBUG - Select project acidplanet
2018-05-31 20:55:08,749 - seesaw.warrior - DEBUG - Start selected project acidplanet (reinstall=False)
2018-05-31 20:55:08,750 - seesaw.warrior - DEBUG - Install project acidplanet
2018-05-31 20:55:08,765 - seesaw.warrior - DEBUG - git clone
2018-05-31 20:55:08,773 - seesaw.warrior - DEBUG - Select project acidplanet
2018-05-31 20:55:09,707 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/acidplanet'...

2018-05-31 20:55:09,709 - seesaw.warrior - ERROR - Custom project install file error
Traceback (most recent call last):
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 507, in install_project
    p.run()
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/externalprocess.py", line 142, in run
    self.pipe = tornado.process.Subprocess(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/process.py", line 244, in __init__
    self.proc = subprocess.Popen(*args, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
2018-05-31 20:55:09,710 - seesaw.warrior - ERROR - Custom installer failed to install: Cloning into '/home/warrior/projects/acidplanet'...
[Errno 8] Exec format error
Custom installer returned 9999

2018-05-31 20:58:31,261 - seesaw.warrior - DEBUG - Select project flickr
2018-05-31 20:58:31,261 - seesaw.warrior - DEBUG - Start selected project flickr (reinstall=False)
2018-05-31 20:58:31,261 - seesaw.warrior - DEBUG - Install project flickr
2018-05-31 20:58:31,262 - seesaw.warrior - DEBUG - git clone
2018-05-31 20:58:37,218 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/flickr'...

2018-05-31 20:58:43,491 - seesaw.warrior - DEBUG - Project install file result: 0
2018-05-31 20:58:43,492 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/flickr'...
The directory '/home/warrior/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Installing Requests
The directory '/home/warrior/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/warrior/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting requests
  Downloading https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl (88kB)
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Downloading https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl (132kB)
Collecting idna<2.7,>=2.5 (from requests)
  Downloading https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl (56kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting certifi>=2017.4.17 (from requests)
  Downloading https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
Installing collected packages: urllib3, idna, chardet, certifi, requests
Successfully installed certifi-2018.4.16 chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Installing warc
The directory '/home/warrior/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/warrior/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting warc
  Downloading https://files.pythonhosted.org/packages/9a/b4/30d87239ec30cd0c504bd7dec9cd22b51ef0cbb00d6fbbc138b1ddcfc108/warc-0.2.1.tar.gz
Installing collected packages: warc
  Running setup.py install for warc: started
    Running setup.py install for warc: finished with status 'done'
Successfully installed warc-0.2.1
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

2018-05-31 20:58:43,492 - seesaw.warrior - DEBUG - Result of the install process: True
2018-05-31 20:58:43,493 - seesaw.warrior - DEBUG - Clone project flickr /home/warrior/projects/flickr
2018-05-31 20:58:43,497 - seesaw.warrior - DEBUG - Cloning version 7379806
2018-05-31 20:58:43,517 - seesaw.warrior - DEBUG - Load pipeline /data/data/projects/flickr-7379806/pipeline.py
2018-05-31 20:58:43,518 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2018-05-31 20:58:43,518 - seesaw.warrior - DEBUG - Executing pipeline
2018-05-31 20:58:43,523 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "<string>", line 22, in <module>
ImportError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 737, in start_selected_project
    pipeline_path, {"downloader": self.downloader})
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 24, in <module>
Exception: Please install requests with 'pip install requests'.
2018-05-31 20:58:43,524 - seesaw.warrior - WARNING - Project flickr did not install correctly and we're ignoring this problem.
2018-05-31 20:58:57,036 - seesaw.warrior - DEBUG - Select project zetaboardsdisco
2018-05-31 20:58:57,037 - seesaw.warrior - DEBUG - Start selected project zetaboardsdisco (reinstall=False)
2018-05-31 20:58:57,037 - seesaw.warrior - DEBUG - Install project zetaboardsdisco
2018-05-31 20:58:57,037 - seesaw.warrior - DEBUG - git clone
2018-05-31 20:58:57,893 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/zetaboardsdisco'...

2018-05-31 20:58:57,893 - seesaw.warrior - WARNING - File /home/warrior/projects/zetaboardsdisco/warrior-install.sh is not executable. Automatically changing it to be executable!
2018-05-31 20:58:57,895 - seesaw.warrior - ERROR - Custom project install file error
Traceback (most recent call last):
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 507, in install_project
    p.run()
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/externalprocess.py", line 142, in run
    self.pipe = tornado.process.Subprocess(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/process.py", line 244, in __init__
    self.proc = subprocess.Popen(*args, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
2018-05-31 20:58:57,897 - seesaw.warrior - ERROR - Custom installer failed to install: Cloning into '/home/warrior/projects/zetaboardsdisco'...
[Errno 8] Exec format error
Custom installer returned 9999

2018-05-31 20:59:07,766 - seesaw.warrior - DEBUG - Select project vidme2
2018-05-31 20:59:07,766 - seesaw.warrior - DEBUG - Start selected project vidme2 (reinstall=False)
2018-05-31 20:59:07,766 - seesaw.warrior - DEBUG - Install project vidme2
2018-05-31 20:59:07,767 - seesaw.warrior - DEBUG - git clone
2018-05-31 20:59:08,718 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/vidme2'...

2018-05-31 20:59:08,718 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/vidme2'...

2018-05-31 20:59:08,719 - seesaw.warrior - DEBUG - Result of the install process: True
2018-05-31 20:59:08,719 - seesaw.warrior - DEBUG - Clone project vidme2 /home/warrior/projects/vidme2
2018-05-31 20:59:08,722 - seesaw.warrior - DEBUG - Cloning version 50e52f0
2018-05-31 20:59:08,741 - seesaw.warrior - DEBUG - Load pipeline /data/data/projects/vidme2-50e52f0/pipeline.py
2018-05-31 20:59:08,741 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2018-05-31 20:59:08,742 - seesaw.warrior - DEBUG - Executing pipeline
2018-05-31 20:59:08,752 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 737, in start_selected_project
    pipeline_path, {"downloader": self.downloader})
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 23, in <module>
  File "/data/data/projects/vidme2-50e52f0/warcio/archiveiterator.py", line 3, in <module>
    from warcio.recordloader import ArcWarcRecordLoader, ArchiveLoadFailed
  File "/data/data/projects/vidme2-50e52f0/warcio/recordloader.py", line 3, in <module>
    from warcio.statusandheaders import StatusAndHeaders
  File "/data/data/projects/vidme2-50e52f0/warcio/statusandheaders.py", line 6, in <module>
    from six.moves import range
ImportError: No module named 'six'
2018-05-31 20:59:08,752 - seesaw.warrior - WARNING - Project vidme2 did not install correctly and we're ignoring this problem.
2018-05-31 20:59:17,598 - seesaw.warrior - DEBUG - Select project roblox
2018-05-31 20:59:17,599 - seesaw.warrior - DEBUG - Start selected project roblox (reinstall=False)
2018-05-31 20:59:17,599 - seesaw.warrior - DEBUG - Install project roblox
2018-05-31 20:59:17,599 - seesaw.warrior - DEBUG - git clone
2018-05-31 20:59:18,459 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/roblox'...

2018-05-31 20:59:18,459 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/roblox'...

2018-05-31 20:59:18,459 - seesaw.warrior - DEBUG - Result of the install process: True
2018-05-31 20:59:18,460 - seesaw.warrior - DEBUG - Clone project roblox /home/warrior/projects/roblox
2018-05-31 20:59:18,462 - seesaw.warrior - DEBUG - Cloning version 2f0e50a
2018-05-31 20:59:18,476 - seesaw.warrior - DEBUG - Load pipeline /data/data/projects/roblox-2f0e50a/pipeline.py
2018-05-31 20:59:18,477 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2018-05-31 20:59:18,477 - seesaw.warrior - DEBUG - Executing pipeline
2018-05-31 20:59:18,496 - seesaw.warrior - DEBUG - Stopped ConfigValue collecting
2018-05-31 20:59:18,498 - seesaw.warrior - INFO - Project roblox installed
```

I get a similar error when manually selecting other projects.  Seems there's something wrong with the install.  I was able to get Roblox working, however.

![screen shot 2018-05-31 at 1 55 16 pm](https://user-images.githubusercontent.com/3498562/40807987-a7ae913a-64da-11e8-89bc-2d10980a2937.png)
![screen shot 2018-05-31 at 1 55 25 pm](https://user-images.githubusercontent.com/3498562/40807989-aaf3317a-64da-11e8-95f0-a2a06f681b10.png)

**Comment by chfoo** [comment]
I think this is the same as #102. The projects causing the error need to be fixed individually.

**Comment by axello** [comment]
I have a similar issue with the Flickr project. Seems some modules cannot be found at the moment:
`2018-07-11 21:02:51,555 - seesaw.warrior - DEBUG - Result of the install process: True
2018-07-11 21:02:51,555 - seesaw.warrior - DEBUG - Clone project flickr /home/warrior/projects/flickr
2018-07-11 21:02:51,560 - seesaw.warrior - DEBUG - Cloning version 7379806
2018-07-11 21:02:51,591 - seesaw.warrior - DEBUG - Load pipeline /data/data/projects/flickr-7379806/pipeline.py
2018-07-11 21:02:51,591 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2018-07-11 21:02:51,591 - seesaw.warrior - DEBUG - Executing pipeline
2018-07-11 21:02:51,596 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "<string>", line 22, in <module>
ImportError: No module named 'requests'
`
I don't see a way to get out of the console (no ^C, ^Z, ^] etc to try to install the pip thing myself.

**Comment by Arkiver2** [comment]
Closing as not relevant to seesaw-kit.
