### ISSUE TITLE
AttributeError: module 'os' has no attribute 'errno'

### ISSUE THREAD

**Issue by marked** [ArchiveTeam/seesaw-kit#115]
File "/home/marked/.local/lib/python3.7/site-packages/seesaw/runner.py", line 187, in _handle_item_output

if e.errno != os.errno.EINTR:
AttributeError: module 'os' has no attribute 'errno'
ERROR:tornado.application:Uncaught exception, closing connection.
Traceback (most recent call last):
File "/home/marked/.local/lib/python3.7/site-packages/seesaw/runner.py", line 182, in _handle_item_output
sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/marked/.local/lib/python3.7/site-packages/tornado/iostream.py", line 562, in wrapper                                                                                                                       return callback(*args)
File "/home/marked/.local/lib/python3.7/site-packages/tornado/stack_context.py", line 345, in wrapped
raise_exc_info(exc)
File "<string>", line 4, in raise_exc_info
File "/home/marked/.local/lib/python3.7/site-packages/tornado/stack_context.py", line 357, in _handle_exception
if tail.exit(*exc):
File "/home/marked/.local/lib/python3.7/site-packages/tornado/stack_context.py", line 188, in exit                                                                                                                     return self.exception_handler(type, value, traceback)
File "/usr/lib/python3.7/contextlib.py", line 239, in helper
return _GeneratorContextManager(func, args, kwds)
File "/usr/lib/python3.7/contextlib.py", line 82, in __init__
self.gen = func(*args, **kwds)
File "/home/marked/.local/lib/python3.7/site-packages/seesaw/pipeline.py", line 51, in handle_item_exception
item.log_output("Failed %s for %s\n" % (task, item.description()))
File "/home/marked/.local/lib/python3.7/site-packages/seesaw/item.py", line 194, in log_output                                                                                                                         self.on_output(self, data)
File "/home/marked/.local/lib/python3.7/site-packages/seesaw/event.py", line 31, in fire                                                                                                                               handler(*args, **kargs)
File "/home/marked/.local/lib/python3.7/site-packages/seesaw/runner.py", line 187, in _handle_item_output
if e.errno != os.errno.EINTR:                                                                                                                                                                                    AttributeError: module 'os' has no attribute 'errno'
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fc6fb8068c8>)
Traceback (most recent call last):
File "/home/marked/.local/lib/python3.7/site-packages/seesaw/runner.py", line 182, in _handle_item_output
sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/marked/.local/lib/python3.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
ret = callback()
File "/home/marked/.local/lib/python3.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
return fn(*args, **kwargs)
File "/home/marked/.local/lib/python3.7/site-packages/tornado/iostream.py", line 562, in wrapper                                                                                                                       return callback(*args)
File "/home/marked/.local/lib/python3.7/site-packages/tornado/stack_context.py", line 345, in wrapped
raise_exc_info(exc)
File "<string>", line 4, in raise_exc_info
File "/home/marked/.local/lib/python3.7/site-packages/tornado/stack_context.py", line 357, in _handle_exception
if tail.exit(*exc):
File "/home/marked/.local/lib/python3.7/site-packages/tornado/stack_context.py", line 188, in exit                                                                                                                     return self.exception_handler(type, value, traceback)
File "/usr/lib/python3.7/contextlib.py", line 239, in helper
return _GeneratorContextManager(func, args, kwds)
File "/usr/lib/python3.7/contextlib.py", line 82, in __init__
self.gen = func(*args, **kwds)
File "/home/marked/.local/lib/python3.7/site-packages/seesaw/pipeline.py", line 51, in handle_item_exception
item.log_output("Failed %s for %s\n" % (task, item.description()))
File "/home/marked/.local/lib/python3.7/site-packages/seesaw/item.py", line 194, in log_output                                                                                                                         self.on_output(self, data)
File "/home/marked/.local/lib/python3.7/site-packages/seesaw/event.py", line 31, in fire                                                                                                                               handler(*args, **kargs)
File "/home/marked/.local/lib/python3.7/site-packages/seesaw/runner.py", line 187, in _handle_item_output
if e.errno != os.errno.EINTR:
AttributeError: module 'os' has no attribute 'errno'

**Comment by JustAnotherArchivist** [comment]
Yeah, `os` had an `import errno` until [this commit](https://github.com/python/cpython/commit/81108375d9b2ccd0add1572da745311d4dfac505), but using it as `os.errno` was never intended.
