### ISSUE TITLE
Running Warrior Extras Installer on archiveteam-warrior-v3.1-20200919.ova does not allow new projects to run  - Wget+At not found/not usable

### ISSUE THREAD

**Issue by Chewie9999** [ArchiveTeam/seesaw-kit#117]
It looks like some dependencies are missing so wget-at fails to be installed at first:

```
Install of wget-at will now begin. 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  926k  100  926k    0     0   971k      0 --:--:-- --:--:-- --:--:--  971k
Selecting previously unselected package wget-at.
(Reading database ... 13395 files and directories currently installed.)
Preparing to unpack wget-at_1.20.3~warrior0_amd64.deb ...
Unpacking wget-at (1.20.3~warrior0) ...
dpkg: dependency problems prevent configuration of wget-at:
 wget-at depends on lua5.1; however:
  Package lua5.1 is not installed.
 wget-at depends on libgnutls-openssl27; however:
  Package libgnutls-openssl27 is not installed.
 wget-at depends on libgnutlsxx28; however:
  Package libgnutlsxx28 is not installed.
 wget-at depends on libgettextpo0; however:
  Package libgettextpo0 is not installed.
 wget-at depends on libpcre2-8-0; however:
  Package libpcre2-8-0 is not installed.

dpkg: error processing package wget-at (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 wget-at
```
Later on dependencies are installed, and then wget-at seems to report that it's been installed correctly:

```
wget-at build ok
Binary path: /opt/wget-at-1.20.3/bin/wget-at
GNU Wget 1.20.3-at.20200919.01, a non-interactive network retriever.
       --lua-script=FILE           load the Lua script from FILE
       --ciphers=STR           Set the priority string (GnuTLS) or cipher list string (OpenSSL) directly.
WARC options:
       --warc-file=FILENAME             save request/response data to a .warc.gz file
       --warc-header=STRING             insert STRING into the warcinfo record
       --warc-max-size=NUMBER           set maximum size of WARC files to NUMBER
       --warc-cdx                       write CDX index files
       --warc-dedup=FILENAME            do not store records listed in this CDX file
       --warc-dedup-disable             disable deduplication of WARC records
       --warc-dedup-url-agnostic        perform URL-agnostic deduplication of WARC records
       --warc-dedup-min-size=NUMBER     minimum payload size to perform deduplication
       --no-warc-compression            do not compress WARC files with GZIP
       --warc-compression-use-zstd      use ZSTD compression for WARC files
       --warc-zstd-dict=FILENAME        the ZSTD compression dictionary to use
       --warc-zstd-dict-no-include      do not prepend ZSTD dictionary to WARC file
       --warc-zstd-dict-no-compression  do not compress the ZSTD dictionary
       --no-warc-digests                do not calculate SHA1 digests
       --no-warc-keep-log               do not store the log file in a WARC record
       --warc-tempdir=DIRECTORY         location for temporary files created by the
                                          WARC writer
Email bug reports, questions, discussions to <bug-wget@gnu.org>
and/or open issues at https://savannah.gnu.org/bugs/?func=additem&group=wget.
=====
wget-at built and installed sucessfully!
=====
===== Done ======
= Software succesfully installed!
= You may now stop this project and select another project.
Finished Install for Item 
Pausing for 60 seconds...
```
However, selecting a new project, eg fotoalbum, then generates an error saying it can't use Wget+At:
```
2020-11-23 18:55:27,935 - seesaw.warrior - DEBUG - git clone
2020-11-23 18:55:29,819 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/fotoalbum'...

2020-11-23 18:55:29,822 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/fotoalbum'...

2020-11-23 18:55:29,823 - seesaw.warrior - DEBUG - Result of the install process: True
2020-11-23 18:55:29,824 - seesaw.warrior - DEBUG - Clone project fotoalbum /home/warrior/projects/fotoalbum
2020-11-23 18:55:29,832 - seesaw.warrior - DEBUG - Cloning version c370017
2020-11-23 18:55:29,962 - seesaw.warrior - DEBUG - Load pipeline /data/data/projects/fotoalbum-c370017/pipeline.py
2020-11-23 18:55:29,964 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2020-11-23 18:55:29,964 - seesaw.warrior - DEBUG - Executing pipeline
2020-11-23 18:55:30,225 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 737, in start_selected_project
    pipeline_path, {"downloader": self.downloader})
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 47, in <module>
Exception: No usable Wget+At found.
2020-11-23 18:55:30,284 - seesaw.warrior - WARNING - Project fotoalbum did not install correctly and we're ignoring this problem.
```

**Comment by Chewie9999** [comment]
Sorry, this should be in the warrior-extras-installer project, please could someone move it.
It may also be related to [this](https://github.com/ArchiveTeam/warrior-extras-installer/issues/1) as I also saw this error a few days ago when I was trying the same thing on a different host.
