### ISSUE TITLE
ModuleNotFoundError: No module named 'zstandard'

### ISSUE THREAD

**Issue by invalidCards** [ArchiveTeam/seesaw-kit#118]
I'm using the official warrior VM running on VirtualBox, and I get the below error whenever I switch to a different project. UrlTeam2 works fine, but all other projects give the below error.

```
2021-01-12 08:53:20,678 - seesaw.warrior - DEBUG - Select project reddit
2021-01-12 08:53:20,691 - seesaw.warrior - DEBUG - Start selected project reddit (reinstall=False)
2021-01-12 08:53:20,692 - seesaw.warrior - DEBUG - Install project reddit
2021-01-12 08:53:20,708 - seesaw.warrior - DEBUG - git clone
2021-01-12 08:53:22,247 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/reddit'...

2021-01-12 08:53:22,249 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/reddit'...

2021-01-12 08:53:22,266 - seesaw.warrior - DEBUG - Result of the install process: True
2021-01-12 08:53:22,266 - seesaw.warrior - DEBUG - Clone project reddit /home/warrior/projects/reddit
2021-01-12 08:53:22,269 - seesaw.warrior - DEBUG - Cloning version df1f600
2021-01-12 08:53:22,286 - seesaw.warrior - DEBUG - Load pipeline /data/data/projects/reddit-df1f600/pipeline.py
2021-01-12 08:53:22,287 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-01-12 08:53:22,287 - seesaw.warrior - DEBUG - Executing pipeline
2021-01-12 08:53:22,637 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 737, in start_selected_project
    pipeline_path, {"downloader": self.downloader})
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 29, in <module>
ModuleNotFoundError: No module named 'zstandard'
2021-01-12 08:53:22,639 - seesaw.warrior - WARNING - Project reddit did not install correctly and we're ignoring this problem.
```

**Comment by mackncheesiest** [comment]
Looks like projects other than UrlTeam2 actually aren't working with the warrior at the moment based on this snippet from the homepage
![image](https://user-images.githubusercontent.com/8922497/104405923-05ee8c00-5556-11eb-929f-faee746f76f8.png)

**Comment by TomGlass** [comment]
Hey this was fixed!
