### ISSUE TITLE
Error during installation of  lua-utf8

### ISSUE THREAD

**Issue by 94bb494nd41f** [ArchiveTeam/seesaw-kit#144]
i am running several warriors on docker on windows and today i got the error below. On the webinterface i do not see any activity although "ArchiveTeams Choice" is selected.

`Traceback (most recent call last):
  File "/home/warrior/start.py", line 23, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.9/subprocess.py", line 1126, in communicate
    self.wait()
  File "/usr/local/lib/python3.9/subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.9/subprocess.py", line 1933, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.9/subprocess.py", line 1891, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
2023-09-11 06:26:24,649 - root - INFO - Logging to /home/warrior/data/warrior.log
2023-09-11 06:26:24,659 - seesaw.warrior - DEBUG - Update warrior hq.
2023-09-11 06:26:24,659 - seesaw.warrior - DEBUG - Warrior ID ''.
2023-09-11 06:26:24,910 - seesaw.warrior - DEBUG - Select project reddit
2023-09-11 06:26:24,911 - seesaw.warrior - DEBUG - Start selected project reddit (reinstall=False)
2023-09-11 06:26:24,912 - seesaw.warrior - DEBUG - Install project reddit
2023-09-11 06:26:24,917 - seesaw.warrior - DEBUG - git pull from https://github.com/ArchiveTeam/reddit-grab
2023-09-11 06:26:25,413 - seesaw.warrior - DEBUG - git operation: hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
2023-09-11 06:26:25,460 - seesaw.warrior - ERROR - Custom installer failed to install: hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
Installing lua-utf8...
Error: Your user does not have write permissions in /usr/local/lib/luarocks/rocks 
-- you may want to run as a privileged user or use your local tree with --local.
Custom installer returned 1
2023-09-11 06:26:25,461 - seesaw.warrior - DEBUG - Result of the install process: False
2023-09-11 06:26:25,461 - seesaw.warrior - WARNING - Project reddit did not install correctly and we're ignoring this problem.
Traceback (most recent call last):
  File "/home/warrior/start.py", line 23, in <module>
    subprocess.run([
  File "/usr/local/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.9/subprocess.py", line 1126, in communicate
    self.wait()
  File "/usr/local/lib/python3.9/subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.9/subprocess.py", line 1933, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.9/subprocess.py", line 1891, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
2023-09-11 06:30:01,589 - root - INFO - Logging to /home/warrior/data/warrior.log
2023-09-11 06:30:01,612 - seesaw.warrior - DEBUG - Update warrior hq.
2023-09-11 06:30:01,622 - seesaw.warrior - DEBUG - Warrior ID ''.
2023-09-11 06:30:03,380 - seesaw.warrior - DEBUG - Select project reddit
2023-09-11 06:30:03,381 - seesaw.warrior - DEBUG - Start selected project reddit (reinstall=False)
2023-09-11 06:30:03,382 - seesaw.warrior - DEBUG - Install project reddit
2023-09-11 06:30:03,387 - seesaw.warrior - DEBUG - git pull from https://github.com/ArchiveTeam/reddit-grab
2023-09-11 06:30:04,099 - seesaw.warrior - DEBUG - git operation: hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
2023-09-11 06:30:04,168 - seesaw.warrior - ERROR - Custom installer failed to install: hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
Installing lua-utf8...
Error: Your user does not have write permissions in /usr/local/lib/luarocks/rocks 
-- you may want to run as a privileged user or use your local tree with --local.
Custom installer returned 1
2023-09-11 06:30:04,170 - seesaw.warrior - DEBUG - Result of the install process: False
2023-09-11 06:30:04,171 - seesaw.warrior - WARNING - Project reddit did not install correctly and we're ignoring this problem.`

**Comment by 94bb494nd41f** [comment]
Updating Docker solved this Problem

**Comment by TheTechRobo** [comment]
Yeah, I believe this is an issue with the warrior container. It's been updated.

**Comment by Arkiver2** [comment]
I will consider this fixed in the image of another project.
