### ISSUE TITLE
[LimitConcurrent] Rsync uploading with missing data directory

### ISSUE THREAD

**Issue by chfoo** [ArchiveTeam/seesaw-kit#48]
Seesaw version: 0.1.4

This is occurring on: ArchiveTeam/wretch-grab/commit/63f87fbf

```
[...lot's of scrolling...]
Uploading with Rsync to rsync://fos.textfiles.com/chfoo/warrior/wretch/chfoo/
Starting RsyncUpload for Item loveohead
sending incremental file list
rsync: change_dir "/home/chris/wretch-grab/data/1387476854ecdf61f810a51cb9-11/" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at flist.c(2027) [sender=3.0.9]
Process RsyncUpload returned exit code 3 for Item loveohead
Failed RsyncUpload for Item loveohead
Retrying after 30 seconds...
Uploading with Rsync to rsync://fos.textfiles.com/chfoo/warrior/wretch/chfoo/
Starting RsyncUpload for Item loveohead
sending incremental file list
rsync: change_dir "/home/chris/wretch-grab/data/1387476854ecdf61f810a51cb9-11/" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at flist.c(2027) [sender=3.0.9]
Process RsyncUpload returned exit code 3 for Item loveohead
Failed RsyncUpload for Item loveohead
Retrying after 30 seconds...
```

Alright, let's see the data dir...

```
chris@droplet1:~/wretch-grab$ ls -halR data
data:
total 12K
drwxrwxr-x 3 chris chris 4.0K Dec 19 20:10 .
drwxr-xr-x 4 chris chris 4.0K Dec 19 10:10 ..
drwxrwxr-x 2 chris chris 4.0K Dec 19 20:13 1387483825d015c6f36e3d5489-12

data/1387483825d015c6f36e3d5489-12:
total 376K
drwxrwxr-x 2 chris chris 4.0K Dec 19 20:13 .
drwxrwxr-x 3 chris chris 4.0K Dec 19 20:10 ..
-rw-rw-r-- 1 chris chris 368K Dec 19 20:13 wretch-loveasy4me-20131219-201026.warc.gz
```

Uh, that's not right.

 _shrugs_

**Comment by tylerknott** [comment]
I have observed this on the bayimg-grab pipeline script. This occured when the [custom "rsync" step](https://github.com/ArchiveTeam/bayimg-grab/blob/81bcb4484ee37be86d0e6d4e1b3f2d126797ce78/pipeline.py#L260) failed. In the web UI the original task disappeared and other tasks continued to process until they reached the "Upload" step of the pipeline script, where they stalled.  Additionally, the web UI reported that there was 1 task on the "Upload" step (when none were) and there were -1 tasks on the "rsync" step.

![bayimg-fail](https://cloud.githubusercontent.com/assets/12749310/14902374/37a28a82-0d60-11e6-9da3-023049e9b04f.png)

In the console the following output was observed for the job:

    Finished WgetDownload for Item 16pictures:nagieaaf
    Starting PrepareStatsForTracker for Item 16pictures:nagieaaf
    Finished PrepareStatsForTracker for Item 16pictures:nagieaaf
    Starting MoveFiles for Item 16pictures:nagieaaf
    Finished MoveFiles for Item 16pictures:nagieaaf
    Starting rsync for Item 16pictures:nagieaaf
    sending incremental file list
    bayimg-16pictures_nagieaaf-20160428-161119_data.txt
                 10 100%    0.00kB/s    0:00:00 (xfr#1, to-chk=0/1)
    
    Failed rsync for Item 16pictures:nagieaaf
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/seesaw/externalprocess.py", line 155, in _handle_subprocess_stdout
        self.on_output(data)
      File "/usr/local/lib/python2.7/dist-packages/seesaw/event.py", line 31, in fire
        handler(*args, **kargs)
      File "/usr/local/lib/python2.7/dist-packages/seesaw/externalprocess.py", line 219, in on_subprocess_stdout
        item.log_output(data, full_line=False)
      File "/usr/local/lib/python2.7/dist-packages/seesaw/item.py", line 81, in log_output
        self.on_output(self, data)
      File "/usr/local/lib/python2.7/dist-packages/seesaw/event.py", line 31, in fire
        handler(*args, **kargs)
      File "/usr/local/lib/python2.7/dist-packages/seesaw/runner.py", line 176, in _handle_item_output
        sys.stdout.write(data)
    IOError: [Errno 4] Interrupted system call
    Waiting 10 seconds...
    Finished rsync for Item 16pictures:nagieaaf
    Starting Upload for Item 16pictures:nagieaaf
    Uploading with Rsync to rsync://fos.textfiles.com/chfoo/warrior/bayimg/MrRadar/
    Starting RsyncUpload for Item 16pictures:nagieaaf
    sending incremental file list
    rsync: change_dir "/home/tyler/bayimg-grab/data/1461877879fddd48305f4eeafa-54/" failed: No such file or directory (2)
    rsync error: errors selecting input/output files, dirs (code 3) at flist.c(2118) [sender=3.1.1]
    Process RsyncUpload returned exit code 3 for Item 16pictures:nagieaaf
    Failed RsyncUpload for Item 16pictures:nagieaaf
    Retrying after 60 seconds...

At that point it appears the job was aborted and a new job started.
