### ISSUE TITLE
Seesaw seems to not be able to get the item json.

### ISSUE THREAD

**Issue by luckcolors** [ArchiveTeam/seesaw-kit#96]
This error seems to happen every time the script tries to get a new item:
```
Starting CheckIP for Item
Finished CheckIP for Item
Starting GetItemFromTracker for Item
Starting CheckIP for Item
Finished CheckIP for Item
Starting GetItemFromTracker for Item
Failed GetItemFromTracker for Item
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/seesaw-0.9-py3.5.egg/seesaw/tracker.py", line 64, in handle_response
    self.process_body(response.body, item)
  File "/usr/local/lib/python3.5/site-packages/seesaw-0.9-py3.5.egg/seesaw/tracker.py", line 125, in process_body
    data = json.loads(body)
  File "/usr/local/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```
I hope you can help me.

**Comment by chfoo** [comment]
Fixed in 07bbaa46 (#91)
